/**
 * Access to the bundled league / team / fixture catalogue.
 *
 * The files under `public/data/` are generated by `scripts/fetch-sports-data.mjs`
 * and committed, so they are served from the app's own origin — no CORS, no API
 * key, and they ship inside the Android APK so the pickers work offline.
 */

export interface Team {
  id: string;
  name: string;
  short: string;
  abbr: string;
}

export interface League {
  id: string;
  /** Sport key from `reference.ts`. */
  sport: string;
  name: string;
  country: string;
  teams: Team[];
}

export interface Catalog {
  generatedAt: string;
  leagues: League[];
}

/** Compact fixture record, as written by the fetch script. */
export interface Fixture {
  id: string;
  /** ISO date-time to minute precision, e.g. "2026-08-22T11:30". */
  d: string;
  /** Home team id. */
  h: string;
  /** Away team id. */
  a: string;
}

export interface FixtureFile {
  generatedAt: string;
  leagues: Record<string, Fixture[]>;
}

export interface ResolvedFixture {
  id: string;
  leagueId: string;
  kickoff: number;
  home: Team;
  away: Team;
  label: string;
}

const EMPTY_CATALOG: Catalog = { generatedAt: '', leagues: [] };
const EMPTY_FIXTURES: FixtureFile = { generatedAt: '', leagues: {} };

/** Resolves a data file path against the deployed base path. */
function dataUrl(file: string): string {
  const base = import.meta.env.BASE_URL || '/';
  return `${base.endsWith('/') ? base : `${base}/`}data/bettracker/${file}`;
}

// Both files are fetched at most once per session and cached as promises, so
// concurrent callers share one request.
let catalogPromise: Promise<Catalog> | null = null;
let fixturePromise: Promise<FixtureFile> | null = null;

async function loadJson<T>(file: string, fallback: T): Promise<T> {
  try {
    const res = await fetch(dataUrl(file));
    if (!res.ok) return fallback;
    return (await res.json()) as T;
  } catch {
    // Missing data must never break the app — the bet form falls back to plain
    // text entry when the catalogue is unavailable.
    return fallback;
  }
}

export function loadCatalog(): Promise<Catalog> {
  catalogPromise ??= loadJson<Catalog>('catalog.json', EMPTY_CATALOG);
  return catalogPromise;
}

export function loadFixtures(): Promise<FixtureFile> {
  fixturePromise ??= loadJson<FixtureFile>('fixtures.json', EMPTY_FIXTURES);
  return fixturePromise;
}

/** Flags used next to league names in the pickers. */
export const COUNTRY_FLAGS: Record<string, string> = {
  US: '🇺🇸',
  GB: '🏴󠁧󠁢󠁥󠁮󠁧󠁿',
  'GB-SCT': '🏴󠁧󠁢󠁳󠁣󠁴󠁿',
  ES: '🇪🇸',
  IT: '🇮🇹',
  DE: '🇩🇪',
  FR: '🇫🇷',
  NL: '🇳🇱',
  PT: '🇵🇹',
  BE: '🇧🇪',
  TR: '🇹🇷',
  AT: '🇦🇹',
  CH: '🇨🇭',
  GR: '🇬🇷',
  RU: '🇷🇺',
  RO: '🇷🇴',
  IL: '🇮🇱',
  DK: '🇩🇰',
  NO: '🇳🇴',
  SE: '🇸🇪',
  EU: '🇪🇺',
};

export function countryFlag(code: string): string {
  return COUNTRY_FLAGS[code] ?? '🏳️';
}

/* ------------------------------------------------------------------ *
 * Lookups
 * ------------------------------------------------------------------ */

export function leaguesForSports(catalog: Catalog, sports: string[]): League[] {
  if (sports.length === 0) return catalog.leagues;
  return catalog.leagues.filter((l) => sports.includes(l.sport));
}

export function findLeague(catalog: Catalog, leagueId: string): League | undefined {
  return catalog.leagues.find((l) => l.id === leagueId);
}

export function findTeam(league: League | undefined, teamId: string): Team | undefined {
  return league?.teams.find((t) => t.id === teamId);
}

/**
 * Upcoming and recent fixtures for a league, resolved to full team objects and
 * sorted by kick-off. `windowDays` looks both back and forward, so a bet being
 * logged the morning after a game still finds it.
 */
export function fixturesForLeague(
  catalog: Catalog,
  fixtures: FixtureFile,
  leagueId: string,
  options: { windowDaysBack?: number; windowDaysForward?: number; now?: number } = {},
): ResolvedFixture[] {
  const league = findLeague(catalog, leagueId);
  if (!league) return [];

  const raw = fixtures.leagues[leagueId] ?? [];
  const now = options.now ?? Date.now();
  const back = (options.windowDaysBack ?? 7) * 86_400_000;
  const forward = (options.windowDaysForward ?? 21) * 86_400_000;

  const byId = new Map(league.teams.map((t) => [t.id, t]));
  const resolved: ResolvedFixture[] = [];

  for (const f of raw) {
    // The stored value has no timezone marker; it is UTC.
    const kickoff = Date.parse(`${f.d}:00Z`);
    if (!Number.isFinite(kickoff)) continue;
    if (kickoff < now - back || kickoff > now + forward) continue;

    const home = byId.get(f.h);
    const away = byId.get(f.a);
    if (!home || !away) continue;

    resolved.push({
      id: f.id,
      leagueId,
      kickoff,
      home,
      away,
      label: `${home.name} - ${away.name}`,
    });
  }

  return resolved.sort((a, b) => a.kickoff - b.kickoff);
}

/** Every fixture of a league regardless of date, for the "all fixtures" view. */
export function allFixturesForLeague(
  catalog: Catalog,
  fixtures: FixtureFile,
  leagueId: string,
): ResolvedFixture[] {
  return fixturesForLeague(catalog, fixtures, leagueId, {
    windowDaysBack: 400,
    windowDaysForward: 400,
  });
}
